spring:
  application:
    name: facade-service

server:
  port: 8082

resilience4j:
  retry:
    instances:
      logging-service:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  circuitbreaker:
    instances:
      logging-service:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        timeoutDuration: 5s

config:
  server:
    url: http://localhost:8888