spring:
  application:
    name: config-server

server:
  port: 8888

services:
  map:
    logging-service:
      host: localhost
      grpcPorts:
        - 9090
        - 9091
        - 9092
      restPorts:
        - 8081
        - 8083
        - 8085

    message-service:
      host: localhost
      restPorts:
        - 8080